name: ▶️ Release
on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: "Select the type of release:"
        required: true
        default: pre-release
        options:
          - major
          - minor
          - patch
          - pre_release
          - pre_release_version

jobs:
  release:
    uses: ./.github/workflows/base-release.yml
    with:
      release-option: "${{github.event.inputs.tag}}"
